apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: receive-forms-api-ingress
  namespace: receive-forms
  labels:
    app.kubernetes.io/name: receive-forms-api
    app.kubernetes.io/part-of: arcobatrox
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`api.form.arcobatrox.com.br`) && PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: receive-forms-api
          port: 80
    - match: Host(`www.api.form.arcobatrox.com.br`) && PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: receive-forms-api
          port: 80
  tls:
    secretName: receive-forms-tls