apiVersion: v1
kind: Service
metadata:
  name: receive-forms-api
  namespace: receive-forms
spec:
  type: ClusterIP
  selector:
    app: receive-forms-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https