apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: receive-forms-app-ingress
  namespace: receive-forms
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`app.form.arcobatrox.com.br`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: receive-forms-app
          port: 80
      # middlewares:
      #   - name: receive-forms-app-redirect-www
      #     namespace: receive-forms
      #   - name: receive-forms-app-redirect-to-https
      #     namespace: receive-forms
    - match: Host(`www.app.form.arcobatrox.com.br`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: receive-forms-app
          port: 80
      # middlewares:
      #   - name: receive-forms-app-redirect-to-https
      #     namespace: receive-forms
  tls:
    secretName: receive-forms-tls
    certResolver: le