apiVersion: v1
kind: Namespace
metadata:
  name: receive-forms
  labels:
    app.kubernetes.io/name: receive-forms
    app.kubernetes.io/part-of: arcobatrox
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
